test:
	g++ `pkg-config --cflags opencv` stero.cpp -g -o stero `pkg-config --libs opencv` 
	./stero
eval:
	g++ `pkg-config --cflags opencv` evaluate.cpp -g -o evaluate `pkg-config --libs opencv`
	./evaluate
